### ISSUE TITLE
loltinder not working?

### ISSUE THREAD

**Issue by ralphamale** [rgr4y/loltinder#1]
Hey, was just wondering if you had any insight on why it's not working anymore. It doesn't display an error message. Let me know. Thanks!

**Comment by stevenirby** [comment]
This stopped working for me as well. The tinderbot authorize method is returning a 403 for me.

Edit:
Opened a ticket for tinderbot. https://github.com/alkawryk/tinderbot/issues/4

```
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty/1.5.8.1</center>
</body>
</html>
```

No error is being thrown, because there is no error property on the body.

```
  this.authorize = function(fbToken, fbId, callback) {
    tinderPost('auth',
      {
        facebook_token: fbToken,
        facebook_id: fbId
      },
      function(error, res, body) {
        if (!error && body.token) {
          xAuthToken = body.token;
          _this.userId = body.user._id;
          callback();
        } else if (body.error){
          throw "Failed to authenticate: " + body.error
        }
      });
  };
```

**Comment by stevenirby** [comment]
This should be working now. Just update npm and it should work.

```
npm update
```

**Comment by andrewtabs** [comment]
I tried npm update and it's still not working.

**Comment by stevenirby** [comment]
@andrewtabs sorry about that, thought it was pushed to npm.

You can point tinderbots dependency for tinderjs to the github branch.
- Go into node_modules/tinderbot
- Open package.json
- Change tinderjs to: `"tinderjs": "git+http://github.com/alkawryk/tinderjs.git#master",`
- Then run `npm install` in node_modules/tinderbot

**Comment by wahab-io** [comment]
is that issue resolved? last i tried last week it wasn't working.

**Comment by fabianschwarzfritz** [comment]
Still not working with updated tinderjs. I got the same error as ralphamale in the first post and now, after the proposed changes, I get a 500 error Access Denied. Any solutions?

**Comment by stevenirby** [comment]
@fabianschwarzfritz are you're running app.js with the the correct auth token?

**Comment by Wenger786** [comment]
I give up this is well broken... I get ....
SyntaxError: Error parsing C:\Users\USER\AppData\Roaming\npm\node_modules\tin
derbot\node_modules\tinderjs\package.json: Unexpected token :
    at Object.parse (native)
    at readPackage (module.js:113:52)
    at tryPackage (module.js:123:13)
    at Function.Module._findPath (module.js:190:18)
    at Function.Module._resolveFilename (module.js:336:25)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\tin
derbot\tinderbot.js:3:14)
    at Module._compile (module.js:456:26)
'expires_in' is not recognized as an internal or external command,
operable program or batch file.

and later ...

'expires_in' is not recognized as an internal or external command,
operable program or batch file.

**Comment by basstwo2k** [comment]
i am the total amateur here, please help me.

when i open package.json in wordpad, it looks like this to me:

{
"name": "loltinder",
"version": "0.0.1",
"dependencies": {},
"devDependencies": {
"underscore": "~1.6.0",
"tinderbot": "*"
},
"engines": {
"node": ">=0.10.0"
}
}

what should i change to make it working?

**Comment by andrewtabs** [comment]
{
  "name": "tinderbot",
  "version": "0.8.6",
  "description": "A platform for developing bots that interact with the Tinder dating app",
  "main": "tinderbot.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/alkawryk/tinderbot.git"
  },
  "author": {
    "name": "alkawryk"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/alkawryk/tinderbot/issues"
  },
  "homepage": "https://github.com/alkawryk/tinderbot",
  "dependencies": {
    "express": "4.0.0",
    "tinderjs": "git+http://github.com/alkawryk/tinderjs.git#master",
    "body-parser": "1.0.1",
    "request": "2.34.0"
  },
  "_id": "tinderbot@0.8.6",
  "dist": {
    "shasum": "6b21f2142a0970c7e8914496b5158c098b39d59c",
    "tarball": "http://registry.npmjs.org/tinderbot/-/tinderbot-0.8.6.tgz"
  },
  "_from": "tinderbot@*",
  "_npmVersion": "1.4.3",
  "_npmUser": {
    "name": "alkawryk",
    "email": "azzro.boy@gmail.com"
  },
  "maintainers": [
    {
      "name": "alkawryk",
      "email": "azzro.boy@gmail.com"
    }
  ],
  "directories": {},
  "_shasum": "6b21f2142a0970c7e8914496b5158c098b39d59c",
  "_resolved": "https://registry.npmjs.org/tinderbot/-/tinderbot-0.8.6.tgz",
  "readme": "ERROR: No README data found!"
}

**Comment by daniel121121** [comment]
It's no longer working for me...
